[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "meteorbase"
version = "0.2.0"
description = "A Python client/API for MeteorBase"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "Ayush Bhattacharya", email = "info.cometlabs@gmail.com" }
]
dependencies = [
    "fastapi==0.116.1",
    "uvicorn[standard]==0.35.0",
    "supabase==2.31.0",
    "python-dotenv==1.2.2",
    "google-genai>=2.20.0",
    "httpx>=0.28.0",
]

[project.urls]
Homepage = "https://github.com/itsjustayush/meteorbaseapi"

[tool.hatch.build.targets.wheel]
packages = ["meteorbase"]